x-airflow-common:
  &airflow-common
  build: .
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__WEBSERVER__WORKERS: 4
    AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  airflow-webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - GUNICORN_CMD_ARGS=""
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    command: ["airflow", "webserver", "--workers", "1", "--debug"]
    volumes:
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./.env:/opt/airflow/.env  # Mount the .env file

  airflow-scheduler:
    <<: *airflow-common
    depends_on:
      - airflow-webserver
      - postgres
    command: ["airflow", "scheduler"]
    volumes:
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./.env:/opt/airflow/.env  # Mount the .env file

  airflow-init:
    <<: *airflow-common
    entrypoint: ["/bin/bash", "-c", "/entrypoint.sh"]
    depends_on:
      - postgres
    command: ["airflow", "db", "migrate"]
    volumes:
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./dags:/opt/airflow/dags
      - ./.env:/opt/airflow/.env  # Mount the .env file
  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8181:8080"  # Spark UI
      - "7077:7077"  # Spark Master Port
  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    depends_on:
      - spark

volumes:
  postgres-db-volume: