x-airflow-common:
  &airflow-common
  build: .
  environment:
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
    AIRFLOW__WEBSERVER__WORKERS: 4
    AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  redis:
    image: redis:latest
    expose:
      - "6379"

  airflow-webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - GUNICORN_CMD_ARGS=""
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["airflow", "webserver", "--workers", "1", "--debug"]
    volumes:
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./dags:/opt/airflow/dags  # Mount local dags folder into the container
      - ./data:/opt/airflow/data

  airflow-scheduler:
    <<: *airflow-common
    depends_on:
      - airflow-webserver
      - postgres
      - redis
    command: ["airflow", "scheduler"]
    volumes:
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./dags:/opt/airflow/dags  # Mount local dags folder into the container
      - ./data:/opt/airflow/data

  airflow-worker:
    <<: *airflow-common
    depends_on:
      - airflow-scheduler
      - redis
      - postgres
    command: ["airflow", "celery", "worker"]
    volumes:
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./dags:/opt/airflow/dags  # Mount local dags folder into the container
      - ./data:/opt/airflow/data

  airflow-init:
    <<: *airflow-common
    entrypoint: ["/bin/bash", "-c", "/entrypoint.sh"]
    depends_on:
      - postgres
      - redis
    command: ["airflow", "db", "migrate"]
    volumes:
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./dags:/opt/airflow/dags  # Mount local dags folder into the container

volumes:
  postgres-db-volume:

